name = "test"
prefix = "test"
author = "Brett"
mainprefix = "z"
include = ["./include"]
files = ["test_x64.dll"]

postbuild = ["!extension"]
releasebuild = ["@zip {{modname}}", "@zip {{key_name}}"]

[scripts.extension]
show_output = true
steps_windows = [
    "cd extension && cargo build --release",
    "copy extension\\target\\release\\test.dll test_x64.dll"
]
steps_linux = [
    "echo \"Unable to build extension on Linux\""
]
